### ISSUE TITLE
Fix token logo

### ISSUE THREAD

**Issue by swengr-janan** [sparkpointio/sparkswap-info#8]
![image](https://user-images.githubusercontent.com/61826995/115661253-bcd97f80-a36f-11eb-83fc-928152da6fc0.png)

**Comment by aldrickb** [comment]
Resolved with pull request #7 . Closing now the issue

![image](https://user-images.githubusercontent.com/51253561/115661578-36716d80-a370-11eb-9651-983d1e60f53b.png)
